/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Woody cafe core
        cafe: {
          bg: '#E8E0D0',
          card: '#F5F0E6',
          nav: '#EDE6D8',
          border: '#C4B99A',
          muted: '#DBD3C1',
          warm: '#F2EBD9',
          deep: '#CFC5AE',
          latte: '#FAF6EE',
        },
        wood: {
          light: '#B8976A',
          mid: '#8B6F47',
          dark: '#5C4A2E',
          bark: '#3D3022',
          grain: '#A38B64',
        },
        ink: {
          DEFAULT: '#2A261F',
          secondary: '#534D42',
          muted: '#7D7668',
          faint: '#A9A295',
          ghost: '#C9C3B5',
        },
        amber: {
          warm: '#8B5E1E',
          mid: '#A06D24',
          light: '#F7EDDA',
          tag: '#B87D2E',
          glow: '#F5D89A',
          soft: '#EDD5A3',
          candle: '#FFE4A8',
        },
        moss: {
          light: '#D4DBC9',
          mid: '#8A9B6E',
          deep: '#5C7044',
          dark: '#3E4D2E',
          sage: '#B5C1A0',
        },
        clay: {
          light: '#E5CDB8',
          mid: '#C4A47A',
          warm: '#B8906A',
          rust: '#9E6B4A',
        },
      },
      fontFamily: {
        sans: ['"Lora"', 'Georgia', 'serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['"Lora"', 'Georgia', 'serif'],
        mono: ['"Courier Prime"', '"Courier New"', 'monospace'],
      },
      borderRadius: {
        card: '14px',
      },
      boxShadow: {
        'warm': '0 2px 12px rgba(92, 74, 46, 0.07)',
        'warm-lg': '0 8px 30px rgba(92, 74, 46, 0.10)',
        'warm-xl': '0 12px 40px rgba(92, 74, 46, 0.12)',
        'inner-warm': 'inset 0 2px 6px rgba(92, 74, 46, 0.05)',
        'glow': '0 0 20px rgba(245, 216, 154, 0.25)',
        'candle': '0 0 30px rgba(255, 228, 168, 0.2)',
        'card': '0 1px 3px rgba(92, 74, 46, 0.04), 0 4px 12px rgba(92, 74, 46, 0.03)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out both',
        'fade-in-up': 'fadeInUp 0.5s ease-out both',
        'fade-in-down': 'fadeInDown 0.4s ease-out both',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-down': 'slideDown 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in-right': 'slideInRight 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in': 'scaleIn 0.3s cubic-bezier(0.16, 1, 0.3, 1) both',
        'breathe': 'breathe 4s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'sway': 'sway 8s ease-in-out infinite',
        'quill-write': 'quillWrite 1.5s ease-out both',
        'ink-spread': 'inkSpread 0.8s ease-out both',
        'page-turn': 'pageTurn 0.6s cubic-bezier(0.16, 1, 0.3, 1) both',
        'word-appear': 'wordAppear 0.3s ease-out both',
        'counter-pulse': 'counterPulse 0.4s ease-out',
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'warm-glow': 'warmGlow 3s ease-in-out infinite alternate',
        'leaf-fall': 'leafFall 12s linear infinite',
        'candle-flicker': 'candleFlicker 2s ease-in-out infinite',
        'grow-in': 'growIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'spin-slow': 'spin 20s linear infinite',
        'drift': 'drift 4s ease-in-out infinite',
        'butterfly': 'butterfly 8s ease-in-out infinite',
        'like-burst': 'likeBurst 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'word-cycle': 'wordCycle 3s ease-in-out both',
        'bounce-subtle': 'bounceSubtle 2s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'ping-slow': 'pingSlow 2s ease-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(28px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.85)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        breathe: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.7' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        sway: {
          '0%, 100%': { transform: 'rotate(-2deg)' },
          '50%': { transform: 'rotate(2deg)' },
        },
        quillWrite: {
          '0%': { width: '0%', opacity: '0' },
          '30%': { opacity: '1' },
          '100%': { width: '100%', opacity: '1' },
        },
        inkSpread: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pageTurn: {
          '0%': { transform: 'rotateY(-8deg) scale(0.96)', opacity: '0' },
          '100%': { transform: 'rotateY(0deg) scale(1)', opacity: '1' },
        },
        wordAppear: {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        counterPulse: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.3)' },
          '100%': { transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        warmGlow: {
          '0%': { boxShadow: '0 0 8px rgba(255, 228, 168, 0.08)' },
          '100%': { boxShadow: '0 0 24px rgba(255, 228, 168, 0.2)' },
        },
        leafFall: {
          '0%': { transform: 'translateY(-10%) translateX(0) rotate(0deg)', opacity: '0' },
          '10%': { opacity: '0.6' },
          '25%': { transform: 'translateY(25vh) translateX(var(--sway, 15px)) rotate(90deg)' },
          '50%': { transform: 'translateY(50vh) translateX(calc(var(--sway, 15px) * -0.7)) rotate(180deg)' },
          '75%': { transform: 'translateY(75vh) translateX(var(--sway, 15px)) rotate(270deg)' },
          '90%': { opacity: '0.6' },
          '100%': { transform: 'translateY(110vh) translateX(0) rotate(360deg)', opacity: '0' },
        },
        candleFlicker: {
          '0%, 100%': { opacity: '0.8', transform: 'scale(1)' },
          '25%': { opacity: '1', transform: 'scale(1.02)' },
          '75%': { opacity: '0.7', transform: 'scale(0.98)' },
        },
        growIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
